<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="33700" started-at="2016-09-25T08:12:59Z" finished-at="2016-09-25T08:13:32Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="33700" started-at="2016-09-25T08:12:59Z" finished-at="2016-09-25T08:13:32Z">
      <class name="testScript.Scenrio_Login">
        <test-method status="PASS" signature="intitalSetup()[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="intitalSetup" is-config="true" duration-ms="109" started-at="2016-09-25T13:42:59Z" finished-at="2016-09-25T13:42:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intitalSetup -->
        <test-method status="PASS" signature="launch_App()[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="launch_App" is-config="true" duration-ms="8615" started-at="2016-09-25T13:42:59Z" finished-at="2016-09-25T13:43:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_App -->
        <test-method status="PASS" signature="Invalid_login(java.util.Map)[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="Invalid_login" duration-ms="2814" started-at="2016-09-25T13:43:08Z" data-provider="InvalidLogin" finished-at="2016-09-25T13:43:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Expected=Sorry we were unable to complete this step because :, UserName=kseyr, Execute=Y, Script_id=Invalid_login, Pwd=syrf, TCID=TC_01, order=1.0}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Invalid_login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="teardown" is-config="true" duration-ms="212" started-at="2016-09-25T13:43:11Z" finished-at="2016-09-25T13:43:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="launch_App()[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="launch_App" is-config="true" duration-ms="8123" started-at="2016-09-25T13:43:11Z" finished-at="2016-09-25T13:43:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_App -->
        <test-method status="PASS" signature="Invalid_login(java.util.Map)[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="Invalid_login" duration-ms="2488" started-at="2016-09-25T13:43:19Z" data-provider="InvalidLogin" finished-at="2016-09-25T13:43:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Expected=Sorry we were unable to complete this step because :, UserName=, Execute=Y, Script_id=Invalid_login, Pwd=, TCID=TC_06, order=1.0}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Invalid_login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="teardown" is-config="true" duration-ms="34" started-at="2016-09-25T13:43:22Z" finished-at="2016-09-25T13:43:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="launch_App()[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="launch_App" is-config="true" duration-ms="7654" started-at="2016-09-25T13:43:22Z" finished-at="2016-09-25T13:43:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_App -->
        <test-method status="FAIL" signature="Valid_login(java.util.Map)[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="Valid_login" duration-ms="3152" started-at="2016-09-25T13:43:29Z" data-provider="ValidLogin" finished-at="2016-09-25T13:43:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Expected=qtpworld2008, UserName=qtpworld2008@gmail.com, Execute=Y, Script_id=Valid_login, Pwd=learn123, TCID=TC_07, order=1.0}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testScript.Scenrio_Login.Valid_login(Scenrio_Login.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Valid_login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testScript.Scenrio_Login@1c62251]" name="teardown" is-config="true" duration-ms="41" started-at="2016-09-25T13:43:32Z" finished-at="2016-09-25T13:43:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testScript.Scenrio_Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
